server:
  port: 80


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: springcloud-zuul

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: order-consumer1

